davidweb/davidweb/urls.py
from django.contrib import admin
from mysite import views
from django.urls import path, include

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('mysite/', views.index),
    path('mysite/chart2/',views.chart),
    path('mysite/our/',views.our),
    path('mysite/datasum/',views.datasum),
]

davidweb/mysite/models.py
from django.db import models

  
class alldata(models.Model):
    
    year_Choice = (
        ('2019', '2019年'),
        ('2020', '2020年'),
        ('2021', '2021年'),
        ('2022', '2022年'),
        ('2023', '2023年'),
    )
    Season_Choice = (
        ('Spring', '春'),
        ('Summer', '夏'),
        ('Autumn', '秋'),
        ('Winter', '冬'),
    )
    area_Choice =  (
        ('North',  '北部'),
        ('Middle', '中部'),
        ('South',  '南部'),
        ('East',   '東部'),
    )
  
    year = models.CharField(max_length = 255,choices= year_Choice)
    season = models.CharField(max_length = 255, choices= Season_Choice)
    area = models.CharField(max_length = 255, choices= area_Choice)
    self_avg = models.DecimalField(max_digits=20, decimal_places=2,blank=True, null=True, default=0)
    industry_avg = models.DecimalField(max_digits=20, decimal_places=2,blank=True, null=True, default=0)


class enddate(models.Model):
    year = models.CharField(max_length = 255)
    month = models.CharField(max_length = 255)

davidweb/mysite/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
import json
from mysite import models
from mysite import filter
import random
import os
 
def index(request):
    alldata = models.alldata.objects.all()
    end = models.enddate.objects.all()
    
    alldataFilter = filter.alldataFilter(queryset=alldata)
    
    if request.method == "POST":
        alldataFilter = filter.alldataFilter(request.POST, queryset=alldata)
 
    context = {
        'alldataFilter': alldataFilter,
        'enddate': end
    }
 
    return render(request, 'mysite/index.html', context)


def chart(request):
    alldata = models.alldata.objects.all()
    end = models.enddate.objects.all()
    alldataFilter = filter.alldataFilter(queryset=alldata)
 
    if request.method == "POST":
        alldataFilter = filter.alldataFilter(request.POST, queryset=alldata)
 
    context = {
        'alldataFilter': alldataFilter,
        'enddate': end
    }
 
    return render(request, 'mysite/chart2.html', context)

def our(request):
    end = models.enddate.objects.all()
    context = {
        'enddate': end
    }
    return render(request, 'mysite/our.html', context)


def datasum(request):
    alldata = models.alldata.objects.all()
    end = models.enddate.objects.all()
    alldataFilter = filter.alldataFilter(queryset=alldata)
 
    if request.method == "POST":
        alldataFilter = filter.alldataFilter(request.POST, queryset=alldata)
 
    context = {
        'alldataFilter': alldataFilter,
        'enddate': end
    }
    return render(request, 'mysite/datasum.html', context)

davidweb/mysite/templates/backup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load mathfilters %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>ECharts</title>
    <!-- 引入刚刚下载的 ECharts 文件 -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.4.2/dist/echarts.min.js"></script>
  </head>
  <style>
    .hide{
      display:none;
    }
  </style>
  <body>
    <form method='POST'>
      {% csrf_token %}
      年份：{{ alldataFilter.form.year }}
      季節：{{ alldataFilter.form.season }}
      <input type="submit" class="btn btn-primary" value="查詢" />

  </form>
  <br />
<table class="table table-bordered table-striped table-hover">
    <thead class="table-light">
        <th class="text-center">年份</th>
        <th class="text-right">季節</th>
        <th class="text-right">地區</th>
        <th class="text-right">自家總用電(度)</th>
        <th class="text-right">企業總用電(度)</th>
    </thead>
    <tbody>
        {% for data in alldataFilter.qs %}
        <tr>
            <td align="center">{{ data.get_year_display }}</td>
            <td align="right">{{ data.get_season_display }}</td>
            <td align="right">{{ data.get_area_display }}</td>
            <td align="right" class = "self">{{ data.self_avg }}</td>
            <td align="right" class = "industry">{{ data.industry_avg }}</td>
        </tr>
        {% endfor %}
    </tbody>
    <tr>
    </tr>
    <tr>
        <td></td>
        <td></td> 
    </tr>
    <tr>
        <td colspan="1" align="center">自家用電量總和</td>
        <td colspan="3" align="right" id='totalself'></td>
    </tr>
    <tr >
        <td colspan="1" align="center">企業用電量總和</td>
        <td colspan="4" align="right" id='totalindustry'></td>        
    </tr>

</table>

  <div id="main" style="width: 900px;height:500px;"></div>
  
  <script type="text/javascript">
  Ndata();
  async function Ndata(){

      var selfavg;
      var totalself=0;
      var Northdata;
      const dataset = [];
      $('td:contains("北部")').next().each(function()
      {
          selfavg=$(this).html();
          totalself+=parseFloat(selfavg);
          $('#totalself').text(totalself.toFixed(2));
          Northdata = totalself;
      });
      console.log(Northdata);
      dataset.push(Northdata);
      console.log(dataset);
  };
      
      // 基于准备好的dom，初始化echarts实例
      var myChart = echarts.init(document.getElementById('main'));
      // 指定图表的配置项和数据
      var option = {
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'cross',
      crossStyle: {
        color: '#999'
      }
    }
  },
  toolbox: {
    feature: {
      dataView: { show: true, readOnly: false },
      magicType: { show: true, type: ['line', 'bar'] },
      restore: { show: true },
      saveAsImage: { show: true }
    }
  },
  legend: {
    data: ['自家用戶', '工業用戶', '自家折線圖', '工業折線圖']
  },
  xAxis: [
    {
      type: 'category',
      data: ['北部', '中部', '南部', '東部'],
      axisPointer: {
        type: 'shadow'
      }
    }
  ],
  yAxis: [
    {
      type: 'value',
      name: '',
      min: 1,
      max: 400,
      interval: 80,
      axisLabel: {
        formatter: '{value} 千萬度'
      }
    },
    {
      type: 'value',
      name: '',
      min: 0,
      max: 25,
      interval: 5,
      axisLabel: {
        formatter: '{value} °C'
      }
    },
    {
      type: 'value',
      name: '',
      min: 0,
      max: 25,
      interval: 5,
      axisLabel: {
        formatter: '{value} °C'
      }
    }
  ],
  series: [
    {
      name: '自家用戶',
      type: 'bar',
      tooltip: {
        valueFormatter: function (value) {
          return value + ' 千萬度';
        }
      },
      data: [
        10
      ]
    },
    {
      name: '工業用戶',
      type: 'bar',
      tooltip: {
        valueFormatter: function (value) {
          return value + ' 千萬度';
        }
      },
      data: [
      {% for data in alldataFilter.qs %}
      {{ data.industry_avg |div:10000000 }},
      {% endfor %}
      ]
    },
    {
      name: '自家折線圖',
      type: 'line',
      yAxisIndex: 1,
      tooltip: {
        valueFormatter: function (value) {
          return value + ' °C';
        }
      },
      data: [2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]
    },
    {
      name: '工業折線圖',
      type: 'line',
      yAxisIndex: 2,
      tooltip: {
        valueFormatter: function (value) {
          return value + ' °C';
        }
      },
      data: [2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]
    }
  ]
};
      // 使用刚指定的配置项和数据显示图表。
      myChart.setOption(option,true);

    </script>
  </body>
</html>

{% endblock  %}

$('td:contains("中部")').next().each(function()
{
  selfavg=$(this).html();
  totalself+=parseFloat(selfavg);
  $('#totalself').text(totalself.toFixed(2));
  Middata = totalself;
});
$('td:contains("南部")').next().each(function()
{
  selfavg=$(this).html();
  totalself+=parseFloat(selfavg);
  $('#totalself').text(totalself.toFixed(2));
  Southdata = totalself;
});
$('td:contains("東部")').next().each(function()
{
  selfavg=$(this).html();
  totalself+=parseFloat(selfavg);
  $('#totalself').text(totalself.toFixed(2));
  Eastdata = totalself;
});
dataset.push(Eastdata);
dataset.push(Southdata);
dataset.push(Middata);
dataset.push(Northdata);
console.log(Northdata);
console.log(dataset);
myChart.config.data.datasets[0].data = dataset[0];
myChart.config.data.datasets[1].data = dataset[1];
myChart.config.data.datasets[2].data = dataset[2];
myChart.config.data.datasets[3].data = dataset[3];
myChart.update();



var Northdata,Middata,Southdata,Eastdata;
const dataset = [];
//將各地區數據導入表格
Ndata();
Mdata();
Sdata();
Edata();

function Ndata(){

  console.log(myChart);
  var selfavg;
  var totalself=0;
  $('td:contains("北部")').next().each(function()
  {
    selfavg=$(this).html();
    totalself+=parseFloat(selfavg);
    $('#totalself').text(totalself.toFixed(2));
    Northdata = totalself;
  });
  dataset.push(Northdata);
  console.log(Northdata);
  console.log(dataset);
  myChart.config.data.datasets[0].data = dataset;
  myChart.update();
}
function Mdata(){

  $('td:contains("中部")').next().each(function()
  {
     var Mselfavg;
     var totalself=0;
     Mselfavg=$(this).html();
     totalself+=parseFloat(Mselfavg);
     $('#Mtotalself').text(totalself.toFixed(2));
     Middata = totalself;
  });
  dataset.push(Middata);
  console.log(Middata);
  console.log(dataset);
  myChart.config.data.datasets[0].data = dataset;
  myChart.update();
}
function Sdata(){

  $('td:contains("南部")').next().each(function()
  {
     var Sselfavg;
     var totalself=0;
     Sselfavg=$(this).html();
     totalself+=parseFloat(Sselfavg);
     $('#Stotalself').text(totalself.toFixed(2));
     Southdata = totalself;
  });
  dataset.push(Southdata);
  console.log(Southdata);
  console.log(dataset);
  myChart.update();

} 
function Edata(){

  $('td:contains("東部")').next().each(function()
  {
     var Eselfavg;
     var totalself=0;
     Eselfavg=$(this).html();
     totalself+=parseFloat(Eselfavg);
     $('#Stotalself').text(totalself.toFixed(2));
     Eastdata = totalself;
  });
  dataset.push(Eastdata);
  console.log(Eastdata);
  console.log(dataset);
  myChart.update();

}     


//////////////////////////////
Ndata();
Mdata();
Sdata();
Edata();

function Ndata(){

  console.log(myChart);
  var selfavg;
  var industryavg;
  var totalself=0;
  var totalindustry=0;
  $('td:contains("北部")').next().each(function()
  {
    selfavg=$(this).html();
    totalself+=parseFloat(selfavg);
    $('#Ntotalself').text(totalself.toFixed(2));
    Northdata = totalself / i;
    dataset.push(Northdata);
    console.log(dataset);
  });
  $('td:contains("北部")').next().next().each(function()
  {
    industryavg=$(this).html();
    totalindustry+=parseFloat(industryavg);
    $('#Ntotalindustry').text(totalindustry.toFixed(2));
    inNorthdata = totalindustry / i;
  });
  console.log(dataset);
  indataset.push(inNorthdata);
  console.log(indataset);
  myChart.config.data.datasets[0].data = dataset;
  myChart.config.data.datasets[1].data = indataset;
  myChart.update();
}

function Mdata(){
  var selfavg;
  var industryavg;
  var totalself=0;
  var totalindustry=0;
  $('td:contains("中部")').next().each(function()
  {
     Mselfavg=$(this).html();
     totalself+=parseFloat(Mselfavg);
     $('#Mtotalself').text(totalself.toFixed(2));
     Middata = totalself / i;
  });
  $('td:contains("中部")').next().next().each(function()
  {
    industryavg=$(this).html();
    totalindustry+=parseFloat(industryavg);
    $('#Mtotalindustry').text(totalindustry.toFixed(2));
    inMiddata = totalindustry / i;
  });

  dataset.push(Middata);
  indataset.push(inMiddata);
  console.log(Middata);
  console.log(dataset);
  console.log(indataset);
  myChart.config.data.datasets[0].data = dataset;
  myChart.config.data.datasets[1].data = indataset;
  myChart.update();
}

function Sdata(){
  var selfavg;
  var industryavg;
  var totalself=0;
  var totalindustry=0;
  $('td:contains("南部")').next().each(function()
  {
     Sselfavg=$(this).html();
     totalself+=parseFloat(Sselfavg);
     $('#Stotalself').text(totalself.toFixed(2));
     Southdata = totalself / i;
  });
  $('td:contains("南部")').next().next().each(function()
  {
    industryavg=$(this).html();
    totalindustry+=parseFloat(industryavg);
    $('#Stotalindustry').text(totalindustry.toFixed(2));
    inSouthdata = totalindustry / i;
  });

  dataset.push(Southdata);
  indataset.push(inSouthdata);
  console.log(Southdata);
  console.log(dataset);
  console.log(indataset);
  myChart.config.data.datasets[0].data = dataset;
  myChart.config.data.datasets[1].data = indataset;
  myChart.update();

} 

function Edata(){
  var Eselfavg;
  var totalself=0;
  var industryavg;
  var totalindustry=0;
  $('td:contains("東部")').next().each(function()
  {
     Eselfavg=$(this).html();
     totalself+=parseFloat(Eselfavg);
     $('#Etotalself').text(totalself.toFixed(2));
     Eastdata = totalself / i;
  });
  $('td:contains("東部")').next().next().each(function()
  {
    industryavg=$(this).html();
    totalindustry+=parseFloat(industryavg);
    $('#Etotalindustry').text(totalindustry.toFixed(2));
    inEastdata = totalindustry / i;
  });

  dataset.push(Eastdata);
  indataset.push(inEastdata);
  console.log(Eastdata);
  console.log(dataset);
  console.log(indataset);
  myChart.config.data.datasets[0].data = dataset;
  myChart.config.data.datasets[1].data = indataset;
  myChart.update();

}       

</script>

davidweb/mysite/templates/mysite/chart2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>圖表</title>
  <!-- 引入下载的 Charts 文件 -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js/dist/chart.umd.min.js"></script>
</head>

<h4 class="text-left">
  {% csrf_token %}
  {% for date in enddate %}
  資料更新截止日期：{{ date.year }} 年
  {{ date.month }} 月
  {% endfor %}
</h4>
<br />

<body style="background-image: url('{% static 'page5.jpg' %}')">
  <form method='POST' id="table">
    {% csrf_token %}
    年份：{{ alldataFilter.form.year }}
    &ensp;季節：{{ alldataFilter.form.season }}
    &ensp;<input type="submit" class="btn btn-primary btn-lg" value="查詢" />&ensp;&ensp;查詢完成後：
    <a class="btn btn-secondary btn-lg" href="#chart">查看圖表</a>
    <a class="btn btn-secondary btn-lg" href="#areasum">查看總和</a>
  </form>
  <br />
  <table class="table table-bordered table-striped table-hover">
    <thead class="table-light">
      <th class="text-center">年份</th>
      <th class="text-right">季節</th>
      <th class="text-right">地區</th>
      <th class="text-right">自家總用電(度)</th>
      <th class="text-right">企業總用電(度)</th>
    </thead>
    <tbody>
      {% for data in alldataFilter.qs %}
      <tr>
        <td align="center">{{ data.get_year_display }}</td>
        <td align="right">{{ data.get_season_display }}</td>
        <td align="right">{{ data.get_area_display }}</td>
        <td align="right" class="self">{{ data.self_avg }}</td>
        <td align="right" class="industry">{{ data.industry_avg }}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>
  <table class="table table-bordered table-striped table-hover" id="areasum">
    <thead class="table-light">
      <th></th>
      <th colspan="3" class="text-right">自家總用電(度)</th>
      <th colspan="4" class="text-right">企業總用電(度)</th>
    </thead>
    <tbody>
      <tr>
        <th class="text-center">北部</td>
        <td colspan="3" align="right" id='Ntotalself'></td>
        <td colspan="4" align="right" id='Ntotalindustry'></td>
      </tr>
      <tr>
        <th class="text-center">中部</td>
        <td colspan="3" align="right" id='Mtotalself'></td>
        <td colspan="4" align="right" id='Mtotalindustry'></td>
      </tr>
      <tr>
        <th class="text-center">南部</td>
        <td colspan="3" align="right" id='Stotalself'></td>
        <td colspan="4" align="right" id='Stotalindustry'></td>
      </tr>
      <tr>
        <th class="text-center">東部</td>
        <td colspan="3" align="right" id='Etotalself'></td>
        <td colspan="4" align="right" id='Etotalindustry'></td>
      </tr>
    </tbody>
  </table>

  <br />

  <br>
  <br>
  <div id="chart" class="chartBox">
    <canvas id="myChart" style="height: 1000px;"></canvas>
    <br>
    <div align="center" class="d-grid gap-2"><a style="font-family: 微軟正黑體; font-size:20px;"
        class="btn btn-secondary btn-lg" href="">返 回 最 上 層 (選單) </a></div>
  </div>
  <style>
    * {
      margin: 0;
      padding: 0;
      font-family: sans-serif;
    }

    .chartBox {
      width: 1100px;
      padding: 20px;
      border-radius: 20px;
      border: solid 3px rgba(54, 162, 235, 1);
      background: white;
      margin: 0 auto;
    }
  </style>

  <script type="text/javascript">


    Chart.defaults.font.size = 20;
    // setup 
    const data = {
      labels: ['北部', '中部', '南部', '東部'],
      datasets: [{
        label: '自家用戶',
        data: [18, 12, 6, 9],
        backgroundColor:
          'rgba(255, 26, 104, 0.5)',
        borderColor:
          'rgba(255, 26, 104, 1)',
        borderWidth: 1
      },
      {
        label: '企業用戶',
        data: [18, 12, 6, 9],
        backgroundColor:
          'rgba(54, 162, 235, 0.5)',
        borderColor:
          'rgba(54, 162, 235, 1)',
        borderWidth: 1
      }
      ]
    };

    // config 
    const config = {
      type: 'bar',
      data,
      options: {
        scales: {
          y: {
            beginAtZero: true,
            ticks: {
              callback: function (value, index, values) {
                return value + ' 億度';
              }
            },
          }
        },
        plugins: {
          tooltip: {
            callbacks: {
              label: function (tooltipItem, data) {
                var label = myChart.data.label;
                var value = myChart.data.datasets[tooltipItem.datasetIndex].data[tooltipItem.dataIndex].toFixed(2)
                return ': ' + value + ' 億度';
              }
            }
          }
        }
      },
    };

    // render init block
    const myChart = new Chart(
      document.getElementById('myChart'),
      config
    );

    //將各地區數據導入表格
    var Northdata = 0, Middata = 0, Southdata = 0, Eastdata = 0, inNorthdata = 0, inMiddata = 0, inSouthdata = 0, inEastdata = 0;
    var dataset = [];
    var indataset = [];
    const i = 100000000;
    //將各地區數據導入表格
    //將各地區數據導入表格
    Ndata();
    Mdata();
    Sdata();
    Edata();
    inNdata();
    inMdata();
    inSdata();
    inEdata();

    function Ndata() {

      console.log(myChart);
      var selfavg;
      var totalself = 0;
      $('td:contains("北部")').next().each(function () {
        selfavg = $(this).html();
        totalself += parseFloat(selfavg);
        $('#Ntotalself').text(totalself.toFixed(2));
        Northdata = totalself / i;
      });
      console.log(Northdata);
      console.log(dataset);
      dataset.push(Northdata);
      myChart.config.data.datasets[0].data = dataset;
      myChart.update();
    }

    function inNdata() {
      console.log(myChart);
      var industryavg;
      var totalin = 0;
      $('td:contains("北部")').next().next().each(function () {
        industryavg = $(this).html();
        totalin += parseFloat(industryavg);
        $('#Ntotalindustry').text(totalin.toFixed(2));
        inNorthdata = totalin / i;
      });
      console.log(inNorthdata);
      indataset.push(inNorthdata);
      console.log(indataset);
      myChart.config.data.datasets[1].data = indataset;
      myChart.update();
    }

    function Mdata() {
      var selfavg;
      var totalself = 0;
      $('td:contains("中部")').next().each(function () {
        selfavg = $(this).html();
        totalself += parseFloat(selfavg);
        $('#Mtotalself').text(totalself.toFixed(2));
        Middata = totalself / i;
      });
      console.log(Middata);
      dataset.push(Middata);
      console.log(dataset);
      myChart.config.data.datasets[0].data = dataset;
      myChart.update();
    }

    function inMdata() {
      console.log(myChart);
      var industryavg;
      var totalin = 0;
      $('td:contains("中部")').next().next().each(function () {
        industryavg = $(this).html();
        totalin += parseFloat(industryavg);
        $('#Mtotalindustry').text(totalin.toFixed(2));
        inMiddata = totalin / i;
      });
      console.log(inMiddata);
      indataset.push(inMiddata);
      console.log(indataset);
      myChart.config.data.datasets[1].data = indataset;
      myChart.update();
    }

    function Sdata() {
      var selfavg;
      var totalself = 0;
      $('td:contains("南部")').next().each(function () {
        selfavg = $(this).html();
        totalself += parseFloat(selfavg);
        $('#Stotalself').text(totalself.toFixed(2));
        Southdata = totalself / i;
      });
      console.log(Southdata);
      dataset.push(Southdata);
      console.log(dataset);
      myChart.config.data.datasets[0].data = dataset;
      myChart.update();
    }

    function inSdata() {
      console.log(myChart);
      var industryavg;
      var totalin = 0;
      $('td:contains("南部")').next().next().each(function () {
        industryavg = $(this).html();
        totalin += parseFloat(industryavg);
        $('#Stotalindustry').text(totalin.toFixed(2));
        inSouthdata = totalin / i;
      });
      console.log(inSouthdata);
      indataset.push(inSouthdata);
      console.log(indataset);
      myChart.config.data.datasets[1].data = indataset;
      myChart.update();
    }

    function Edata() {
      var selfavg;
      var totalself = 0;
      $('td:contains("東部")').next().each(function () {
        selfavg = $(this).html();
        totalself += parseFloat(selfavg);
        $('#Etotalself').text(totalself.toFixed(2));
        Eastdata = totalself / i;
      });
      console.log(Eastdata);
      dataset.push(Eastdata);
      console.log(dataset);
      myChart.config.data.datasets[0].data = dataset;
      myChart.update();
    }

    function inEdata() {
      console.log(myChart);
      var industryavg;
      var totalin = 0;
      $('td:contains("東部")').next().next().each(function () {
        industryavg = $(this).html();
        totalin += parseFloat(industryavg);
        $('#Etotalindustry').text(totalin.toFixed(2));
        inEastdata = totalin / i;
      });
      console.log(inEastdata);
      indataset.push(inEastdata);
      console.log(indataset);
      myChart.config.data.datasets[1].data = indataset;
      myChart.update();
    }



  </script>
</body>

</html>
{% endblock %}

davidweb/mysite/templates/mysite/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script>
        $(document).ready(function () {
            var selfavg;
            var totalself = 0;
            $('td:nth-child(4)').each(function () {
                selfavg = $(this).html();
                totalself += parseFloat(selfavg);
                $('#totalself').text(totalself.toFixed(2));
            });

        });

    </script>
    <script>
        $(document).ready(function () {
            var industryavg;
            var totalin = 0;
            $('td:nth-child(5)').each(function () {
                industryavg = $(this).html();
                totalin += parseFloat(industryavg);
                $('#totalindustry').text(totalin.toFixed(2));
            });

        });

    </script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<h4 class="text-left">
    {% csrf_token %}
    {% for date in enddate %}
    資料更新截止日期：{{ date.year }} 年
    {{ date.month }} 月
    {% endfor %}
</h4>
<br />

<body style="background-image: url('{% static 'page5.jpg' %}')">

    <form method='POST'>
        {% csrf_token %}
        年份：{{ alldataFilter.form.year }}
        &ensp;季節：{{ alldataFilter.form.season }}
        &ensp;地區：{{ alldataFilter.form.area }}
        &ensp;<input type="submit" class="btn btn-primary btn-lg" value="查詢" />&ensp;&ensp;&ensp;查詢完成後：
        <a type="submit" class="btn btn-secondary btn-lg" href="#areasum">查看選項總和</a>
    </form>
    <br />
    <table class="table table-bordered table-striped table-hover">
        <thead class="table-light">
            <th class="text-center">年份</th>
            <th class="text-right">季節</th>
            <th class="text-right">地區</th>
            <th class="text-right">自家總用電(度)</th>
            <th class="text-right">企業總用電(度)</th>
        </thead>
        <tbody>
            {% for data in alldataFilter.qs %}
            <tr>
                <td align="center">{{ data.get_year_display }}</td>
                <td align="right">{{ data.get_season_display }}</td>
                <td align="right">{{ data.get_area_display }}</td>
                <td align="right">{{ data.self_avg }}</td>
                <td align="right">{{ data.industry_avg }}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tr id="areasum">
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td colspan="1" align="center">自家用電量總和</td>
            <td colspan="3" align="right" id='totalself'></td>
        </tr>
        <tr>
            <td colspan="1" align="center">企業用電量總和</td>
            <td colspan="4" align="right" id='totalindustry'></td>
        </tr>

    </table>
    <div align="center" class="d-grid gap-2"><a style="font-family: 微軟正黑體; font-size:20px;"
            class="btn btn-secondary btn-lg" href="">返 回 最 上 層 (選單) </a></div>
    </div>
    <br>
    <br>
    <br>
    {% endblock %}